### ISSUE TITLE
Shiny Tabs

### ISSUE THREAD

**Issue by tokazakiuw** [tokazakiuw/BF1_final_project#7]
TAB 1: Graph Values over Time; filter graph by demographic

TAB 2: Leaflet plot by location; filter graph by demographic. 

TAB 3: Table summarizing data; calculate values.

**Comment by aolbap** [comment]
https://catalog.data.gov/dataset/heart-disease-mortality-data-among-us-adults-35-by-state-territory-and-county-2016-2018

**Comment by tokazakiuw** [comment]
added tabs
